# config/meta.yml
meta_title: "Venga - Trouvez votre coach sportif à Bruxelles !"
meta_description: "Venga est le premier abonnement de sport universel qui vous permet de trouver votre coach sportif idéal en fonction de l'activité que vous voulez pratiquer. "
meta_image: "metavenga.png" # Une image dans votre dossier app/assets/images/
